namespace Markwardt.NetChannel.Internal;

/// <summary>
/// The cryptographic primitives the wire protocol is built from (Docs/Wire.md), implemented by
/// <see cref="NetCrypto"/>.
/// </summary>
internal interface INetCrypto
{
    /// <summary>
    /// Generates a random value of the given length, suitable for a server secret or a cookie's random
    /// component.
    /// </summary>
    /// <param name="length">The number of random bytes to generate.</param>
    /// <returns>The generated bytes.</returns>
    byte[] GenerateRandom(int length);

    /// <summary>
    /// Creates a fresh ephemeral X25519 key pair for one side of a connection handshake.
    /// </summary>
    /// <returns>The key pair.</returns>
    NetAgreementKey CreateAgreementKey();

    /// <summary>
    /// Deterministically re-derives the ephemeral X25519 key pair a server uses for one handshake attempt, from
    /// a 32-byte seed computed from its own server secret and the attempt's context, so the attempt's private
    /// key never needs to be stored (Docs/Wire.md#connection-handshake).
    /// </summary>
    /// <param name="seed">The 32-byte seed to derive the key pair from.</param>
    /// <returns>The key pair.</returns>
    NetAgreementKey CreateAgreementKey(ReadOnlySpan<byte> seed);

    /// <summary>
    /// Signs a message with an Ed25519 private key.
    /// </summary>
    /// <param name="privateKey">The 32-byte Ed25519 private key seed.</param>
    /// <param name="message">The message to sign.</param>
    /// <returns>The 64-byte signature.</returns>
    byte[] Sign(ReadOnlyMemory<byte> privateKey, ReadOnlySpan<byte> message);

    /// <summary>
    /// Verifies an Ed25519 signature.
    /// </summary>
    /// <param name="publicKey">The 32-byte Ed25519 public key.</param>
    /// <param name="message">The message the signature was supposedly made over.</param>
    /// <param name="signature">The signature to verify.</param>
    /// <returns><see langword="true"/> if the signature verifies; otherwise, <see langword="false"/>.</returns>
    bool Verify(ReadOnlySpan<byte> publicKey, ReadOnlySpan<byte> message, ReadOnlySpan<byte> signature);

    /// <summary>
    /// Derives key material from existing keying material via HKDF-SHA256.
    /// </summary>
    /// <param name="key">The input keying material.</param>
    /// <param name="salt">The salt, or empty for none.</param>
    /// <param name="info">The context/application-specific info string.</param>
    /// <param name="length">The number of bytes to derive.</param>
    /// <returns>The derived key material.</returns>
    byte[] DeriveKey(ReadOnlySpan<byte> key, ReadOnlySpan<byte> salt, ReadOnlySpan<byte> info, int length);

    /// <summary>
    /// Computes an HMAC-SHA256 over the given data.
    /// </summary>
    /// <param name="key">The MAC key.</param>
    /// <param name="data">The data to authenticate.</param>
    /// <returns>The 32-byte HMAC output.</returns>
    byte[] ComputeHmacSha256(ReadOnlySpan<byte> key, ReadOnlySpan<byte> data);

    /// <summary>
    /// Encrypts and authenticates a value with ChaCha20-Poly1305.
    /// </summary>
    /// <param name="key">The 32-byte symmetric key.</param>
    /// <param name="nonce">The 12-byte nonce.</param>
    /// <param name="associatedData">Additional data authenticated but not encrypted.</param>
    /// <param name="plaintext">The value to encrypt.</param>
    /// <returns>The ciphertext, with the 16-byte authentication tag appended.</returns>
    byte[] Seal(ReadOnlySpan<byte> key, ReadOnlySpan<byte> nonce, ReadOnlySpan<byte> associatedData, ReadOnlySpan<byte> plaintext);

    /// <summary>
    /// Decrypts and verifies a value sealed by <see cref="Seal"/>.
    /// </summary>
    /// <param name="key">The 32-byte symmetric key.</param>
    /// <param name="nonce">The 12-byte nonce.</param>
    /// <param name="associatedData">Additional data authenticated but not encrypted.</param>
    /// <param name="sealedValue">The ciphertext, with its 16-byte authentication tag appended.</param>
    /// <returns>The decrypted value, or <see langword="null"/> if authentication failed.</returns>
    byte[]? Open(ReadOnlySpan<byte> key, ReadOnlySpan<byte> nonce, ReadOnlySpan<byte> associatedData, ReadOnlySpan<byte> sealedValue);

    /// <summary>
    /// Computes a CRC32C (Castagnoli) checksum.
    /// </summary>
    /// <param name="data">The data to checksum.</param>
    /// <returns>The checksum.</returns>
    uint ComputeCrc32C(ReadOnlySpan<byte> data);
}

/// <summary>
/// An ephemeral X25519 key pair used to derive a connection's session and payload keys (Docs/Wire.md#session-key-derivation).
/// </summary>
internal sealed class NetAgreementKey(NSec.Cryptography.Key key) : IDisposable
{
    /// <summary>
    /// This side's public key, sent to the other side of the handshake.
    /// </summary>
    public ReadOnlyMemory<byte> PublicKey { get; } = key.PublicKey.Export(NSec.Cryptography.KeyBlobFormat.RawPublicKey);

    /// <summary>
    /// Combines this key pair's private key with the other side's public key to compute a shared secret, then
    /// derives key material from it via HKDF-SHA256, without ever exposing the raw shared secret.
    /// </summary>
    /// <param name="remotePublicKey">The other side's public key.</param>
    /// <param name="salt">The salt, or empty for none.</param>
    /// <param name="info">The context/application-specific info string.</param>
    /// <param name="length">The number of bytes to derive.</param>
    /// <returns>The derived key material.</returns>
    public byte[] DeriveKey(ReadOnlyMemory<byte> remotePublicKey, ReadOnlySpan<byte> salt, ReadOnlySpan<byte> info, int length)
    {
        NSec.Cryptography.PublicKey remote = NSec.Cryptography.PublicKey.Import(NSec.Cryptography.KeyAgreementAlgorithm.X25519, remotePublicKey.Span, NSec.Cryptography.KeyBlobFormat.RawPublicKey);
        using NSec.Cryptography.SharedSecret sharedSecret = NSec.Cryptography.KeyAgreementAlgorithm.X25519.Agree(key, remote)
            ?? throw new InvalidOperationException("X25519 key agreement failed.");

        return NSec.Cryptography.KeyDerivationAlgorithm.HkdfSha256.DeriveBytes(sharedSecret, salt, info, length);
    }

    /// <inheritdoc cref="IDisposable.Dispose" />
    public void Dispose() => key.Dispose();
}

/// <inheritdoc cref="INetCrypto" />
internal sealed class NetCrypto : INetCrypto
{
    private static readonly uint[] Crc32CTable = BuildCrc32CTable();

    /// <inheritdoc />
    public byte[] GenerateRandom(int length) => RandomNumberGenerator.GetBytes(length);

    /// <inheritdoc />
    public NetAgreementKey CreateAgreementKey() => new(NSec.Cryptography.Key.Create(NSec.Cryptography.KeyAgreementAlgorithm.X25519));

    /// <inheritdoc />
    public NetAgreementKey CreateAgreementKey(ReadOnlySpan<byte> seed) =>
        new(NSec.Cryptography.Key.Import(NSec.Cryptography.KeyAgreementAlgorithm.X25519, seed, NSec.Cryptography.KeyBlobFormat.RawPrivateKey));

    /// <inheritdoc />
    public byte[] Sign(ReadOnlyMemory<byte> privateKey, ReadOnlySpan<byte> message)
    {
        using NSec.Cryptography.Key key = NSec.Cryptography.Key.Import(NSec.Cryptography.SignatureAlgorithm.Ed25519, privateKey.Span, NSec.Cryptography.KeyBlobFormat.RawPrivateKey);
        return NSec.Cryptography.SignatureAlgorithm.Ed25519.Sign(key, message);
    }

    /// <inheritdoc />
    public bool Verify(ReadOnlySpan<byte> publicKey, ReadOnlySpan<byte> message, ReadOnlySpan<byte> signature)
    {
        NSec.Cryptography.PublicKey key = NSec.Cryptography.PublicKey.Import(NSec.Cryptography.SignatureAlgorithm.Ed25519, publicKey, NSec.Cryptography.KeyBlobFormat.RawPublicKey);
        return NSec.Cryptography.SignatureAlgorithm.Ed25519.Verify(key, message, signature);
    }

    /// <inheritdoc />
    public byte[] DeriveKey(ReadOnlySpan<byte> key, ReadOnlySpan<byte> salt, ReadOnlySpan<byte> info, int length) =>
        HKDF.DeriveKey(HashAlgorithmName.SHA256, key.ToArray(), length, salt.IsEmpty ? null : salt.ToArray(), info.ToArray());

    /// <inheritdoc />
    public byte[] ComputeHmacSha256(ReadOnlySpan<byte> key, ReadOnlySpan<byte> data) => HMACSHA256.HashData(key, data);

    /// <inheritdoc />
    public byte[] Seal(ReadOnlySpan<byte> key, ReadOnlySpan<byte> nonce, ReadOnlySpan<byte> associatedData, ReadOnlySpan<byte> plaintext)
    {
        using ChaCha20Poly1305 aead = new(key);
        byte[] sealedValue = new byte[plaintext.Length + 16];
        aead.Encrypt(nonce, plaintext, sealedValue.AsSpan(0, plaintext.Length), sealedValue.AsSpan(plaintext.Length, 16), associatedData);
        return sealedValue;
    }

    /// <inheritdoc />
    public byte[]? Open(ReadOnlySpan<byte> key, ReadOnlySpan<byte> nonce, ReadOnlySpan<byte> associatedData, ReadOnlySpan<byte> sealedValue)
    {
        if (sealedValue.Length < 16)
        {
            return null;
        }

        using ChaCha20Poly1305 aead = new(key);
        byte[] plaintext = new byte[sealedValue.Length - 16];

        try
        {
            aead.Decrypt(nonce, sealedValue[..plaintext.Length], sealedValue[plaintext.Length..], plaintext, associatedData);
            return plaintext;
        }
        catch (AuthenticationTagMismatchException)
        {
            return null;
        }
    }

    /// <inheritdoc />
    public uint ComputeCrc32C(ReadOnlySpan<byte> data)
    {
        uint crc = uint.MaxValue;

        foreach (byte b in data)
        {
            crc = Crc32CTable[(crc ^ b) & 0xFF] ^ (crc >> 8);
        }

        return crc ^ uint.MaxValue;
    }

    private static uint[] BuildCrc32CTable()
    {
        const uint Polynomial = 0x82F63B78;
        uint[] table = new uint[256];

        for (uint i = 0; i < 256; i++)
        {
            uint value = i;

            for (int bit = 0; bit < 8; bit++)
            {
                value = (value & 1) != 0 ? (value >> 1) ^ Polynomial : value >> 1;
            }

            table[i] = value;
        }

        return table;
    }
}
